version: "3.4"

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher

  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini

  resource:
    image: semtech/mu-cl-resources:1.22.2
    links:
      - triplestore:triplestore
    volumes:
      - ./config/resources:/config

  producer:
    image: redpencil/fragmentation-producer:0.4.0
    environment:
      BASE_URL: "http://data.lblod.info/ext"
      FOLDER_DEPTH: 1
      PAGE_RESOURCES_COUNT: 10
      LDES_STREAM_PREFIX: "http://data.lblod.info/streams/lpdc/"
      TIME_TREE_RELATION_PATH: "http://www.w3.org/ns/prov#generatedAtTime"
      CACHE_SIZE: 10
      DATA_FOLDER: "/data"
      ENABLE_AUTH: "false"
    volumes:
      - "./data/ldes-feed/:/data/"

  consumer:
    image: redpencil/ldes-consumer
    environment:
      CRON_PATTERN: "*/30 * * * * *"
      LDES_STREAM: http://producer/example-stream
      LDES_ENDPOINT_VIEW: http://producer/example-stream/1
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
