version: "3.4"

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      ERROR_ON_UNWRITTEN_DATA: "true"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.22.2
    links:
      - database:database
    volumes:
      - ./config/resources:/config

  producer:
    image: redpencil/fragmentation-producer:0.4.0
    environment:
      BASE_URL: "http://data.lblod.info/ext"
      FOLDER_DEPTH: 1
      PAGE_RESOURCES_COUNT: 10
      LDES_STREAM_PREFIX: "http://data.lblod.info/streams/lpdc/"
      TIME_TREE_RELATION_PATH: "http://www.w3.org/ns/prov#generatedAtTime"
      CACHE_SIZE: 10
      DATA_FOLDER: "/data"
      ENABLE_AUTH: "false"
    volumes:
      - "./data/ldes-feed/:/data/"

  consumer:
    image: redpencil/ldes-consumer
    environment:
      CRON_PATTERN: "*/15 * * * * *"
      LDES_STREAM: http://producer/example-stream
      LDES_ENDPOINT_VIEW: http://producer/example-stream/1
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/ldes"

  # Metis
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
  resource-labels:
    image: lblod/resource-label-service:0.3.2
>>>>>>> feature/demo1
